
name: test_line_notify
on:
  schedule:
    - cron: '0 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy
          pip install selenium
          pip install requests
          pip install beautifulsoup4
      - name: Run script
        run: |
          python qwe.py
